from enum import IntEnum
from ..mixins import EnumMixin

class Messagetypes(EnumMixin, IntEnum):
    """
    The message type.
    """

    DEFAULT = 0
    RECIPIENT_ADD = 1
    RECIPIENT_REMOVE = 2
    CALL = 3
    CHANNEL_NAME_CHANGE = 4
    CHANNEL_ICON_CHANGE = 5
    CHANNEL_PINNED_MESSAGE = 6
    GUILD_MEMBER_JOIN = 7
    USER_PREMIUM_GUILD_SUBSCRIPTION = 8
    USER_PREMIUM_GUILD_SUBSCRIPTION_TIER_1 = 9
    USER_PREMIUM_GUILD_SUBSCRIPTION_TIER_2 = 10
    USER_PREMIUM_GUILD_SUBSCRIPTION_TIER_3 = 11
    CHANNEL_FOLLOW_ADD = 12
    GUILD_DISCOVERY_DISQUALIFIED = 13
    GUILD_DISCOVERY_REQUALIFIED = 14
    USER_NOTE_UPDATE = 15
    GUILD_EMOJIS_UPDATE = 16
    GUILD_INTEGRATIONS_UPDATE = 17